FROM arm32v7/python:3.5-slim-buster

WORKDIR /app

RUN apt update
RUN apt install gcc libjpeg-dev zlib1g-dev build-essential liblapack-dev libblas-dev -y

RUN pip install --upgrade pip
RUN pip install ptvsd==4.1.3

COPY requirements.txt ./

RUN pip install -r requirements.txt

RUN pip install https://storage.googleapis.com/tensorflow/raspberrypi/tensorflow-2.3.0-cp35-none-linux_armv7l.whl

COPY . .

CMD [ "python3", "-u", "./main.py" ]