FROM arm32v7/python:3.7-slim-buster

WORKDIR /app

RUN apt update
RUN apt install gcc libjpeg-dev zlib1g-dev -y

COPY requirements.txt ./
RUN pip install -r requirements.txt
RUN pip install https://storage.googleapis.com/tensorflow/raspberrypi/tensorflow-2.3.0-cp35-none-linux_armv7l.whl

COPY . .

CMD [ "python3", "-u", "./main.py" ]