FROM amd64/python:3.7-slim-buster

WORKDIR /app

RUN pip install ptvsd==4.1.3
COPY requirements.txt ./
RUN pip install -r requirements.txt

RUN pip install tensorflow==2.6

COPY . .

CMD [ "python3", "-u", "./main.py" ]